spring.profiles.active: develop
server:
  port: 8090

---

spring.config.activate.on-profile: develop

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false

  springdoc:
    swagger-ui:
      path=/swagger-ui.html

---
spring.h2.activate.on-profile: enabled

spring.config.activate.on-profile: test
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false